### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by fjcalderons** [tko22/eth-voting-dapp#1]
I just had a problem when I run npm install, I don't know if something is missing or I just need to do something else before install, this is the error in the log

```
11597 silly pacote trying ms@0.7.3 by hash: sha1-cIFVpeROM/X9D8U+gdDUCpG+H/8=
11598 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
11598 verbose stack     at writeAfterEnd (_stream_writable.js:237:12)
11598 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
11598 verbose stack     at PassThrough.Writable.end (_stream_writable.js:573:10)
11598 verbose stack     at ReadEntry.entry.on (/usr/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
11598 verbose stack     at ReadEntry.emit (events.js:165:20)
11598 verbose stack     at ReadEntry.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
11598 verbose stack     at ReadEntry.[maybeEmitEnd] (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
11598 verbose stack     at ReadEntry.end (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
11598 verbose stack     at Unpack.[consumeBody] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
11598 verbose stack     at Unpack.[consumeChunkSub] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
11598 verbose stack     at Unpack.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
11598 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
11598 verbose stack     at Unzip.emit (events.js:160:13)
11598 verbose stack     at Unzip.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
11598 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
11598 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
11599 verbose cwd /home/fran/dev/eth-voting-dapp
11600 verbose Linux 4.13.0-32-generic
11601 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
11602 verbose node v9.5.0
11603 verbose npm  v5.7.1
11604 error code ERR_STREAM_WRITE_AFTER_END
11605 error write after end
11606 verbose exit [ 1, true ]
```

Node: v9.5.0
npm: 5.7.1

**Comment by tko22** [comment]
hm... did you `npm install -g truffle`? This command installs truffle globally but it shouldn't make a difference. I've never ran into this error, but try recloning it and `npm install`.

**Comment by piercebhunt** [comment]
try`sudo npm install -g truffle` 

Not sure if this will help you with your error as my error was because of my mac's permission settings.

**Comment by swqtc** [comment]
候选人ID怎么得到啊
